version: "3"

services:
  server:
    container_name: "central_worker_service_server"
    build: .
    command: "./main server"
    ports:
      - "9095:9095"
  
  worker:
    container_name: "central_worker_service_worker"
    build: .
    command: "./main worker"

  telebot:
    container_name: "central_worker_service_telegram_bot"
    build: .
    command: "./main telegram-bot"
