version: "3"

services:
  server:
    image: "central_service"
    build:
      context: .
      dockerfile: Dockerfile
    command: "./main server"
    ports:
      - "9095:9095"
    volumes:
      - /var/local_storage/image/:/var/local_storage/media/image/
  
  worker:
    command: "./main worker"
    image: "central_service"
    depends_on:
      - server
    volumes:
      - /var/local_storage/image/:/var/local_storage/media/image/

  telebot:
    command: "./main telegram-bot"
    image: "central_service"
    depends_on:
      - server
    volumes:
      - /var/local_storage/image/:/var/local_storage/media/image/

  siakad_scraper:
    command: "./main siakad-scraper"
    image: "central_service"
    depends_on:
      - server
    volumes:
      - /var/local_storage/image/:/var/local_storage/media/image/
    
